/**
 * GeneratedSection — the "Generated by Cakra" shelf in the Artifact Gallery.
 *
 * Lists artifacts saved from Cakra chat (artifactStore): open in the
 * sandboxed viewer, rename, delete. The gallery owns the meta list (it
 * also feeds the hero count) and hands it down; this section mirrors it
 * into the organism graph so generated artifacts join the mesh.
 */
import { Suspense, lazy, useEffect, useState } from 'react'
import { AppWindow, Bot, FileText, Pencil, Shapes, Trash2 } from 'lucide-react'
import type { ArtifactSpec, ArtifactType } from '../cakra/lib/artifactProtocol'
import { mirrorCollection } from '../../lib/core/sync'
import { cssVar, tint } from '../../design-system/tokens'
import { useLang } from '../../lib/i18n'
import {
  deleteGenerated,
  getGeneratedContent,
  renameGenerated,
  type GeneratedArtifactMeta,
} from './lib/artifactStore'

const ArtifactViewer = lazy(() => import('./generated/ArtifactViewer'))

const TYPE_ICONS: Record<ArtifactType, typeof AppWindow> = {
  html: AppWindow,
  svg: Shapes,
  markdown: FileText,
}

interface Props {
  metas: GeneratedArtifactMeta[]
  onChange: (metas: GeneratedArtifactMeta[]) => void
}

export default function GeneratedSection({ metas, onChange }: Props) {
  const { t } = useLang()
  const [viewing, setViewing] = useState<ArtifactSpec | null>(null)

  useEffect(() => {
    mirrorCollection('artifact', 'artifacts', metas, {
      id: m => m.id,
      title: m => m.title,
      data: m => ({ type: m.type, size: m.size, createdAt: m.createdAt }),
    })
  }, [metas])

  if (metas.length === 0) return null

  const open = async (meta: GeneratedArtifactMeta) => {
    const content = await getGeneratedContent(meta.id)
    if (content == null) return
    setViewing({ type: meta.type, title: meta.title, content, complete: true })
  }

  const rename = (meta: GeneratedArtifactMeta) => {
    const title = window.prompt(t('artifacts.renamePrompt'), meta.title)
    if (title?.trim()) onChange(renameGenerated(meta.id, title.trim()))
  }

  const remove = async (meta: GeneratedArtifactMeta) => {
    if (!window.confirm(`${t('artifacts.delete')} "${meta.title}"?`)) return
    onChange(await deleteGenerated(meta.id))
  }

  return (
    <div className="px-8 pb-2">
      <div className="max-w-6xl mx-auto">
        <div className="flex items-center gap-2 mb-3">
          <Bot size={14} style={{ color: 'var(--c-cakra)' }} />
          <span className="text-xs uppercase tracking-[0.25em] font-semibold" style={{ color: 'var(--c-cakra)' }}>
            {t('artifacts.generated')}
          </span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 mb-6">
          {metas.map(meta => {
            const Icon = TYPE_ICONS[meta.type]
            return (
              <div
                key={meta.id}
                className="flex items-center gap-3 rounded-xl border border-hair p-3 transition-colors"
                style={{ background: 'color-mix(in srgb, var(--c-cakra) 5%, transparent)' }}
              >
                <button
                  onClick={() => open(meta)}
                  className="press flex items-center gap-3 flex-1 min-w-0 text-left"
                  title={t('artifacts.open')}
                >
                  <span
                    className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0"
                    style={{ background: 'color-mix(in srgb, var(--c-cakra) 15%, transparent)', color: 'var(--c-cakra)' }}
                  >
                    <Icon size={16} />
                  </span>
                  <span className="flex-1 min-w-0">
                    <span className="block truncate text-sm font-medium" style={{ color: cssVar('text') }}>
                      {meta.title}
                    </span>
                    <span className="block text-[10px] uppercase tracking-wider" style={{ color: cssVar('text2') }}>
                      {meta.type} · {new Date(meta.createdAt).toLocaleDateString()}
                    </span>
                  </span>
                </button>
                <button
                  onClick={() => rename(meta)}
                  className="press p-1.5 rounded-lg transition-colors"
                  style={{ color: cssVar('text2'), background: tint('xenon', 7) }}
                  title={t('artifacts.rename')}
                  aria-label={`${t('artifacts.rename')} ${meta.title}`}
                >
                  <Pencil size={12} />
                </button>
                <button
                  onClick={() => remove(meta)}
                  className="press p-1.5 rounded-lg transition-colors"
                  style={{ color: cssVar('c-danger'), background: tint('c-danger', 10) }}
                  title={t('artifacts.delete')}
                  aria-label={`${t('artifacts.delete')} ${meta.title}`}
                >
                  <Trash2 size={12} />
                </button>
              </div>
            )
          })}
        </div>
      </div>

      {viewing && (
        <Suspense fallback={null}>
          <ArtifactViewer artifact={viewing} onClose={() => setViewing(null)} />
        </Suspense>
      )}
    </div>
  )
}
